---
version: "2.1"
services:
  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: TQH-downloadmanager
    hostname: TQH-downloadmanager
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - pyloaddownloader:/config
      - /srv/TQH/downloads:/downloads
    ports:
      - 8000:8000
      - 9666:9666 #optional
    network_mode: bridge
    restart: unless-stopped
volumes:
  pyloaddownloader:

